.PHONY: html

html:
	python -m markdown README.md > html/README.html
	python -m markdown ruby.md > html/ruby.html
	python -m markdown python.md > html/python.html
	python -m markdown perl.md > html/perl.html
	python -m markdown php.md > html/php.html
	python -m markdown javascript.md > html/javascript.html
	python -m markdown java.md > html/java.html
	python -m markdown golang.md > html/golang.html
	python -m markdown console_tools.md > html/console_tools.html
	python -m markdown web_service.md > html/web_service.html
